/**
 * @module @devcore/shared/types/model
 * AI model configuration and usage tracking type definitions.
 * Defines provider enums, role-based model assignments, and
 * default configurations for the multi-model orchestration system.
 */

/**
 * Supported AI provider platforms.
 * Each provider offers different models with varying capabilities and pricing.
 */
export enum AIProvider {
  /** OpenAI — GPT-5.6 Sol, Terra, Luna and related models. */
  OPENAI = 'openai',
  /** Anthropic — Claude Fable 5, Sonnet 5, Opus 4.8 and related models. */
  ANTHROPIC = 'anthropic',
  /** Google — Gemini 3.1 Pro, 3.5 Flash and related models. */
  GOOGLE = 'google',
}

/**
 * Functional roles that AI models can be assigned to within the pipeline.
 * Different roles require different model capabilities and configurations.
 */
export enum ModelRole {
  /** Plans task execution strategy and breaks down requirements. */
  PLANNER = 'planner',
  /** Designs system architecture and high-level technical decisions. */
  ARCHITECT = 'architect',
  /** Generates code implementations based on plans and architecture. */
  IMPLEMENTER = 'implementer',
  /** Reviews code for quality, correctness, and best practices. */
  REVIEWER = 'reviewer',
  /** Generates and executes test cases for implementations. */
  TESTER = 'tester',
  /** Handles lightweight, low-latency tasks requiring quick responses. */
  FAST = 'fast',
}

/**
 * Configuration for an AI model assigned to a specific role.
 * Includes provider details, generation parameters, and pricing information.
 */
export interface ModelConfig {
  /** The AI provider platform hosting this model. */
  provider: AIProvider;
  /** The specific model identifier (e.g., 'gpt-5.6-sol', 'claude-fable-5'). */
  modelId: string;
  /** The functional role this model is configured for. */
  role: ModelRole;
  /** Maximum number of tokens the model can generate in a single response. */
  maxTokens: number;
  /** Sampling temperature controlling response randomness (0.0–2.0). */
  temperature: number;
  /** Cost per input token in USD (e.g., 0.0000025 for $2.50 per million). */
  costPerInputToken: number;
  /** Cost per output token in USD (e.g., 0.00001 for $10.00 per million). */
  costPerOutputToken: number;
}

/**
 * Tracks actual token usage and cost for a single AI model invocation.
 * Used for billing, budgeting, and usage analytics.
 */
export interface ModelUsage {
  /** The AI provider that served the request. */
  provider: AIProvider;
  /** The specific model identifier that processed the request. */
  modelId: string;
  /** Number of input tokens consumed by the request. */
  inputTokens: number;
  /** Number of output tokens generated by the model. */
  outputTokens: number;
  /** Total monetary cost of this invocation in USD. */
  cost: number;
  /** Timestamp when the invocation occurred. */
  timestamp: Date;
}

/**
 * Default model configurations for each functional role in the pipeline.
 * These defaults provide a balanced setup optimizing for quality, speed, and cost.
 * Can be overridden per-project or per-task as needed.
 */
export const DEFAULT_MODEL_CONFIG: Record<ModelRole, ModelConfig> = {
  [ModelRole.PLANNER]: {
    provider: AIProvider.OPENAI,
    modelId: 'gpt-5.6-sol',
    role: ModelRole.PLANNER,
    maxTokens: 8192,
    temperature: 0.7,
    costPerInputToken: 5 / 1_000_000,
    costPerOutputToken: 30 / 1_000_000,
  },
  [ModelRole.ARCHITECT]: {
    provider: AIProvider.OPENAI,
    modelId: 'gpt-5.6-sol',
    role: ModelRole.ARCHITECT,
    maxTokens: 8192,
    temperature: 0.5,
    costPerInputToken: 5 / 1_000_000,
    costPerOutputToken: 30 / 1_000_000,
  },
  [ModelRole.IMPLEMENTER]: {
    provider: AIProvider.ANTHROPIC,
    modelId: 'claude-fable-5',
    role: ModelRole.IMPLEMENTER,
    maxTokens: 128000,
    temperature: 0.3,
    costPerInputToken: 10 / 1_000_000,
    costPerOutputToken: 50 / 1_000_000,
  },
  [ModelRole.REVIEWER]: {
    provider: AIProvider.OPENAI,
    modelId: 'gpt-5.6-terra',
    role: ModelRole.REVIEWER,
    maxTokens: 8192,
    temperature: 0.3,
    costPerInputToken: 2.5 / 1_000_000,
    costPerOutputToken: 15 / 1_000_000,
  },
  [ModelRole.TESTER]: {
    provider: AIProvider.GOOGLE,
    modelId: 'gemini-3.5-flash',
    role: ModelRole.TESTER,
    maxTokens: 8192,
    temperature: 0.2,
    costPerInputToken: 0.15 / 1_000_000,
    costPerOutputToken: 0.6 / 1_000_000,
  },
  [ModelRole.FAST]: {
    provider: AIProvider.OPENAI,
    modelId: 'gpt-5.6-luna',
    role: ModelRole.FAST,
    maxTokens: 4096,
    temperature: 0.5,
    costPerInputToken: 1 / 1_000_000,
    costPerOutputToken: 6 / 1_000_000,
  },
} as const;
