/**
 * @module @devcore/providers/types
 * Core type definitions for the AI provider abstraction layer.
 */

import type { AIProvider } from '@devcore/shared';

/**
 * Represents the role of a participant in a chat conversation.
 * - `'system'` — System-level instructions that guide the model's behavior.
 * - `'user'` — Messages from the end user.
 * - `'assistant'` — Messages generated by the AI model.
 */
export type ChatRole = 'system' | 'user' | 'assistant';

/**
 * A single message within a chat conversation.
 */
export interface ChatMessage {
  /** The role of the message author. */
  readonly role: ChatRole;

  /** The text content of the message. */
  readonly content: string;

  /** An optional display name for the message author. */
  readonly name: string | undefined;
}

/**
 * A request payload sent to an AI provider's chat completion endpoint.
 */
export interface ChatRequest {
  /** The ordered list of messages that comprise the conversation context. */
  readonly messages: ChatMessage[];

  /** The model identifier to use for this request (e.g. `'gpt-4o'`, `'claude-sonnet-4-20250514'`). */
  readonly model: string;

  /**
   * The maximum number of tokens the model may generate in its response.
   * When `undefined`, the provider's default limit is used.
   */
  readonly maxTokens: number | undefined;

  /**
   * Sampling temperature controlling randomness (0 = deterministic, 2 = very random).
   * When `undefined`, the provider's default temperature is used.
   */
  readonly temperature: number | undefined;

  /**
   * An optional system-level prompt prepended to the conversation.
   * Some providers handle this as a dedicated parameter rather than a system message.
   */
  readonly systemPrompt: string | undefined;

  /**
   * The expected response format.
   * - `'text'` — Free-form text (default).
   * - `'json'` — The model should respond with valid JSON.
   * When `undefined`, defaults to `'text'`.
   */
  readonly responseFormat: 'text' | 'json' | undefined;
}

/**
 * The parsed response from an AI provider's chat completion endpoint.
 */
export interface ChatResponse {
  /** The generated text content. */
  readonly content: string;

  /** The model identifier that actually served the request. */
  readonly model: string;

  /** Token usage statistics for this request/response cycle. */
  readonly usage: {
    /** Number of tokens consumed by the input (prompt + context). */
    readonly inputTokens: number;
    /** Number of tokens generated in the output. */
    readonly outputTokens: number;
  };

  /**
   * The reason the model stopped generating tokens.
   * - `'stop'` — Natural completion or stop sequence reached.
   * - `'length'` — Maximum token limit reached.
   * - `'error'` — An error occurred during generation.
   */
  readonly finishReason: 'stop' | 'length' | 'error';

  /**
   * The raw, unprocessed response from the provider's API.
   * Useful for debugging or accessing provider-specific fields.
   */
  readonly rawResponse: unknown | undefined;
}

/**
 * A unified adapter interface that normalises interactions with different AI providers.
 *
 * Each concrete adapter (OpenAI, Anthropic, Google, etc.) implements this interface
 * so that callers can switch providers without changing application code.
 */
export interface AIProviderAdapter {
  /**
   * Sends a chat completion request and returns the parsed response.
   *
   * @param request - The chat request payload.
   * @returns A promise that resolves to the provider-normalised response.
   * @throws If the request fails after all retry attempts are exhausted.
   */
  chat(request: ChatRequest): Promise<ChatResponse>;

  /**
   * Lists all model identifiers supported by this adapter.
   *
   * @returns A promise that resolves to an array of model ID strings.
   */
  listModels(): Promise<string[]>;

  /**
   * Estimates the monetary cost (in USD) for a given token usage.
   *
   * @param inputTokens  - Number of input tokens consumed.
   * @param outputTokens - Number of output tokens generated.
   * @returns The estimated cost in USD.
   */
  estimateCost(inputTokens: number, outputTokens: number): number;

  /** The canonical AI provider enum value this adapter represents. */
  readonly provider: AIProvider;

  /** The model identifier this adapter is configured to use by default. */
  readonly modelId: string;
}
